include("initial_points.jl")
include("problems.jl")
include("projections.jl")
include("functions.jl")
# include("algorithms/framework2.jl")
# include("algorithms/MOPCGM.jl")
# include("algorithms/GMOPCGM.jl")
# include("algorithms/CGPM.jl")
# include("algorithms/GCGPM.jl")
# include("algorithms/STTDFPM.jl")
include("algorithms/LSFDFPM.jl")
